services:
  # Backend API Service
  - type: web
    name: chimera-backend-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main_agents:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GOOGLE_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
  
  # Frontend Static Site
  - type: web
    name: chimera-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend-react && npm install && npm run build
    staticPublishPath: frontend-react/dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://chimera-backend-api.onrender.com
